services:
  app:
    build: .
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - composer_cache:/root/.composer/cache
    ports:
      - "9000:9000"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      LOG_CHANNEL: errorlog
      APP_URL: https://cat-platform.web.id
      DB_CONNECTION: pgsql
      DB_HOST: ep-lucky-firefly-a5ep9avf.aws-us-east-2.pg.laravel.cloud
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: npg_wMb6N4HclOEm

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

  vite-build:
    image: node:20-alpine
    restart: "no"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: >
      sh -c "
      npm install &&
      npm install @rollup/rollup-linux-x64-musl lightningcss-linux-x64-musl @tailwindcss/oxide-linux-x64-musl -D --force &&
      npm run build
      "

volumes:
  composer_cache:
