services:
  app:
    build: .
    # restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
      - composer_cache:/root/.composer/cache
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      LOG_CHANNEL: stack
      APP_URL: http://localhost:9000
      DB_CONNECTION: mysql
      DB_HOST: 192.168.65.254
      DB_PORT: 3306
      DB_DATABASE: cat_apps
      DB_USERNAME: cat_user
      DB_PASSWORD: secret
      SESSION_DRIVER: file
      CACHE_STORE: file
      QUEUE_CONNECTION: sync
    command: >
      sh -c "
      rm -f bootstrap/cache/*.php &&
      php artisan package:discover --ansi &&
      php artisan optimize:clear &&
      php artisan migrate --database=mysql --force &&
      php artisan db:seed --database=mysql --force &&
      php artisan serve --host=0.0.0.0 --port=9000
      "

  vite:
    image: node:20-alpine
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    command: >
      sh -c "
      npm install --include=optional &&
      npm install @rollup/rollup-linux-x64-musl lightningcss-linux-x64-musl @tailwindcss/oxide-linux-x64-musl -D --force &&
      npm run dev -- --host
      "

volumes:
  composer_cache:
  vendor:
